data:
  train_path: "/home/nfs/inf6/data/datasets/ThermalDBs/Freiburg/train"
  val_path: "/home/nfs/inf6/data/datasets/ThermalDBs/Freiburg/val"
  test_path: "/home/nfs/inf6/data/datasets/ThermalDBs/Freiburg/test"
  annotations_path: "/home/nfs/inf6/data/cudalab/victorv1/data"
  img_width: 224
  img_height: 224
  num_workers: 4

device : "cuda"

# Training configuration
training:
  batch_size: 2
  epochs: 30
  lr: 1.0e-4
  weight_decay: 1.0e-5
  print_freq: 10
  save_freq: 5
  warmup_epochs: 5
  lr_init: 1e-4
  lr_min: 1e-6
  annotations_path: "/home/nfs/inf6/data/cudalab/victorv1/data"
  results: "/home/nfs/inf6/data/cudalab/victorv1/results"


# Evaluation configuration
evaluation:
  batch_size: 2
  vis_samples: 10

# AIS test data configuration
ais_test:
  data_path: "/home/nfs/inf6/data/datasets/ThermalDBs/AIS"